### ISSUE TITLE
v0.3 release TODOs

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/KeywordSearch.jl#6]
I want to make a breaking 0.3 release and register it in General. First...
- [x] Improve docs, add quick tutorial (#8)
- [x] Add docs badges (#8)
- [x] Rename to `Document` and `Corpus` (#4)
- [x] Remove `And` (#5), since it's breaking so better to do it now
- [x] Improve table interface (#7) since it's breaking
